# Generated by Django 2.2.12 on 2020-10-24 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_campania_lime', models.IntegerField(verbose_name='Codi campania Lime')),
                ('fecha_extraccion_lime', models.DateField(verbose_name='Data extracció Lime')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('import_date', models.DateField(verbose_name='Data importació')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo_campania_lime', models.IntegerField(verbose_name='Codi tipus campanya Lime')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_encuesta_lime', models.IntegerField(verbose_name='Codi enquesta Lime')),
                ('sid_lime', models.IntegerField(verbose_name='sid')),
                ('name', models.CharField(max_length=1024, verbose_name='Nom')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid_lime', models.IntegerField(verbose_name='Cod pregunta Lime')),
                ('tid_lime', models.IntegerField(verbose_name='Cod enquestat Lime')),
                ('name', models.CharField(max_length=500, verbose_name='Nom')),
                ('bloq_type', models.CharField(max_length=1, verbose_name='Tipus bloc')),
                ('prof_name', models.CharField(max_length=50, verbose_name='Nom professor')),
                ('prof_surname1', models.CharField(max_length=50, verbose_name='Cognom1 professor')),
                ('prof_surname2', models.CharField(max_length=50, verbose_name='Cognom2 professor')),
                ('original_value', models.CharField(max_length=2000, verbose_name='Comentari original')),
                ('new_value', models.CharField(max_length=2000, verbose_name='Comentari nou')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.IssueType')),
                ('solution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.SolutionType')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='type_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.CampaignType'),
        ),
    ]
