# Generated by Django 2.2.12 on 2020-11-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bloq_type',
            new_name='block_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='prof_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='prof_surname1',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='prof_surname2',
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_lime', models.IntegerField(verbose_name='sid')),
                ('num_prof_lime', models.CharField(max_length=2, verbose_name='Num. professor')),
                ('name', models.CharField(max_length=50, verbose_name='Nom professor')),
                ('surname1', models.CharField(max_length=50, verbose_name='Cognom1 professor')),
                ('surname2', models.CharField(max_length=50, verbose_name='Cognom2 professor')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.Professor'),
        ),
    ]
