# Generated by Django 2.2.12 on 2020-11-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0003_auto_20201122_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.CharField(max_length=500, null=True, verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='comment',
            name='question_id_lime',
            field=models.CharField(max_length=5, null=True, verbose_name='Cod pregunta Lime'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.IssueType'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='new_value',
            field=models.CharField(max_length=2000, null=True, verbose_name='Comentari nou'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='qid_lime',
            field=models.IntegerField(verbose_name='qid Lime'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='solution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.SolutionType'),
        ),
    ]
