# Generated by Django 2.2.12 on 2020-11-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0004_auto_20201122_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='issue_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='solution_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='changed',
            field=models.BooleanField(default=False, verbose_name='Modificat'),
        ),
        migrations.CreateModel(
            name='CommentSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.Comment')),
                ('solution_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.SolutionType')),
            ],
        ),
        migrations.CreateModel(
            name='CommentIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.Comment')),
                ('issue_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.IssueType')),
            ],
        ),
    ]
