# Generated by Django 2.2.12 on 2021-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0005_auto_20201122_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCampania',
            fields=[
                ('cod_tipo_campania', models.AutoField(db_column='COD_TIPO_CAMPANIA', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=100, null=True)),
                ('editable', models.CharField(db_column='EDITABLE', max_length=1)),
                ('fecha_modificacion', models.DateTimeField(blank=True, db_column='FECHA_MODIFICACION', null=True)),
                ('usuario_modificacion', models.CharField(blank=True, db_column='USUARIO_MODIFICACION', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TIPO_CAMPANIA',
                'managed': True,
            },
        ),
    ]
