# Generated by Django 2.2.12 on 2021-03-19 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0006_tipocampania'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.IssueType'),
        ),
        migrations.AddField(
            model_name='comment',
            name='solution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.SolutionType'),
        ),
    ]
