# Generated by Django 2.2.12 on 2021-03-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0007_auto_20210319_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocampania',
            options={'managed': False},
        ),
    ]
