# Generated by Django 2.2.12 on 2021-03-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0008_auto_20210319_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='block_type',
            field=models.CharField(max_length=1, verbose_name='Tipus pregunta'),
        ),
    ]
