# Generated by Django 2.2.12 on 2021-03-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0009_auto_20210325_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.IssueType'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='solution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.SolutionType'),
        ),
    ]
