# Generated by Django 2.2.12 on 2021-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0011_auto_20210428_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue_types',
            field=models.ManyToManyField(through='tfmsurveysapp.CommentIssue', to='tfmsurveysapp.IssueType'),
        ),
    ]
