# Generated by Django 2.2.12 on 2021-05-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfmsurveysapp', '0012_auto_20210506_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='issue_types',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tfmsurveysapp.IssueType'),
        ),
    ]
